# Generated by Django 4.1.3 on 2022-11-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Marca', models.CharField(max_length=50)),
                ('Modelo', models.CharField(max_length=50)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['Valor'],
            },
        ),
    ]
