# Generated by Django 4.1.3 on 2022-11-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='Nome',
        ),
    ]
